First release of databricks.ManagedTableDataset
kedro-org/kedro-plugins pull request #127
Opened 2023-03-14 01:55 UTC by dannyrfar

## Description

## Development notes

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

2023-03-14 01:58 UTC, dannyrfar commented
hey @noklam just saw your comment in the other PR. I did see those two datasets, this will be more focused on Databricks Unity catalog tables. The SparkDataSet and DeltaTableDataSets are for interfacing with files directly. Both can be used on databricks but are intended for different purposes.

2023-04-12 21:40 UTC, jmholzer reviewed
A great start, thanks for this. I haven't yet manually tested this or tried to follow the logic too closely. It would be good if you could take me through this on a call.

The tests look fine, though I have left a few comments on style and correctness in `managed_table_dataset.py`.

In addition:
- There are quite a few comments I didn't make about things that I think running `make lint` on your project would fix, you should do this. This is currently why the `lint` check is failing.
- Tests are failing on Python 3.8 - 3.10 because the test `TestManagedTableDataSet::test_load_pandas` is failing. They are failing on 3.7 because the requirements call for a version of `mlflow` that doesn't support 3.7.

2023-04-12 21:40 UTC, jmholzer commented on kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py
> +            "version": self._version,
```suggestion
            "version": str(self._version),
```

For consistency with the generic `Dict[str, str]`.

2023-04-12 22:38 UTC, jmholzer commented on kedro-datasets/test_requirements.txt
> +mlflow==2.2.1
```suggestion
mlflow~=2.2.1; python_version>='3.8'
mlflow~=1.30.0; python_version=='3.7'
```

This dataset needs to support Python 3.7. [`mlflow 1.30.0` was the last version of `mlflow` to support 3.7](https://github.com/mlflow/mlflow/releases/tag/v2.0.1).

I would also use a compatible release operator here, not `==`.

2023-04-13 17:42 UTC, maria-olivia-lihn reviewed
i would have a test where the unity catalog name contains a dash (as it used to fail)

2023-04-13 17:42 UTC, maria-olivia-lihn commented on kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py
> +    _NAMING_REGEX = r"\b[0-9a-zA-Z_-]{1,32}\b"
We incorporated dash support in naming regex with the following: 

`    _NAMING_REGEX = r"\b[0-9a-zA-Z_\-]{1,32}\b"
`

2023-04-14 14:23 UTC, maria-olivia-lihn requested changes

2023-04-14 14:23 UTC, maria-olivia-lihn commented on kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py
> +                self._get_spark().sql(f"USE CATALOG {self._table.catalog}")
catalog should be between back tick marks as well: 
`
self._get_spark().sql(f"USE CATALOG `{self._table.catalog}`")`

2023-05-05 00:17 UTC, jmholzer commented
I made a few changes:

- I added tests to reach 100% coverage in `managed_table_dataset`.
- I removed the functions for automatically getting and updating the version cache (and the version cache itself) as all of these were unused (and untested). They are not necessary for the dataset to function, and in other datasets we do not use this approach. They also introduced unnecessary dependencies. If we decide we want the functionality they intended (?) to offer, we can always add this in a future PR.
- I removed a walrus operator, as we need to support Python 3.7 :).

2023-05-22 09:59 UTC, closed without merging