build: loosen the Python version requirement
kedro-org/kedro-plugins pull request #276
Opened 2023-07-20 12:09 UTC by sbrugman

## Description
Start for https://github.com/kedro-org/kedro-plugins/issues/265

This won't have any direct impact as all plugins require `kedro` which is not available for 3.11.
It does however loosen the circular dependency which we have now.

Frankly, there is little reason not to upgrade asap. 
(Some datasets that are too slow to update can just be only available for 3.10)

## Development notes

## Checklist

- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Updated the documentation to reflect the code changes
- [X] Added a description of this change in the relevant `RELEASE.md` file
- [X] Added tests to cover my changes

2023-07-26 17:34 UTC, astrojuanlu requested changes
I don't even like having this upper bound in there, some past discussion:

https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special

(and also https://discuss.python.org/t/requires-python-upper-limits/12663?u=astrojuanlu)

So I'd rather evaluate whether we could lift the upper version uncapped for all the plugins, and whether we need something like https://github.com/kedro-org/kedro/pull/2742 for, say, `kedro-datasets` (which is a bit hairy).

2023-08-09 20:32 UTC, sbrugman commented
I agree. There isn't anything preventing us from doing so, is there?

2023-08-10 10:05 UTC, astrojuanlu commented
`kedro-telemetry` was already lifted in #292, and with `kedro-datasets` we want to be a bit more careful and the team has it on the radar #154 

I'd say let's wait for Kedro 0.18.13 (which will have Python 3.11 support https://github.com/kedro-org/kedro/pull/2851) and then let the team evaluate each plugin case by case. `telemetry` will probably be trivial, `datasets` not so much (although most of the heavy lifting has already been done), and no idea about `docker` and `airflow`.

2023-08-26 11:45 UTC, astrojuanlu commented
Better to close this PR and open one per remaining plugin, thanks @sbrugman!

2023-08-26 11:45 UTC, closed without merging