build(telemetry): Release 0.2.5
kedro-org/kedro-plugins pull request #291
Opened 2023-08-02 16:41 UTC by SajidAlamQB

## Description

Release kedro-telemetry 0.2.5

## Development notes

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

2023-08-02 16:48 UTC, ankatiyar approved these changes

2023-08-02 16:54 UTC, merelcht requested changes
I don't think we should be making actual changes to the code base as part of a release. The open-bound should go in separately IMO.

2023-08-02 16:57 UTC, SajidAlamQB commented
> I don't think we should be making actual changes to the code base as part of a release. The open-bound should go in separately IMO.

That's fair.

2023-08-03 09:22 UTC, merelcht approved these changes

2023-08-03 10:59 UTC, merged