cloudpickle is an interesting extension of the pickle functionality.
kedro-org/kedro-plugins pull request #361
Opened 2023-09-30 10:09 UTC by hfwittmann

## Description

Quote from their github: "cloudpickle makes it possible to serialize Python constructs not supported by the default pickle module from the Python standard library."

Its already implicity supported by kedro / kedro-plugins, but would be useful to have it in the docs.

## Development notes

Changed the documentation
Added cloudpickle to the unit tests

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

2023-09-30 14:37 UTC, noklam approved these changes
Thanks for the PR!

2023-10-01 15:25 UTC, datajoely commented
Love this! Question for the group, should we think about changing the default pickle engine to something a bit more ML ready?

2023-10-02 08:26 UTC, marrrcin commented
Cloudpickle is really good, we use it by default in Kedro-AzureML/Sagemaker/VertexAI 💪🏻

2023-10-02 08:28 UTC, marrrcin requested changes

2023-10-02 08:28 UTC, marrrcin commented on kedro-datasets/setup.py
> +    "cloudpickle<=2.0.0 ",
There's a whitespace at the end of this string.

2023-10-02 08:31 UTC, stichbury commented
> Its already implicity supported by kedro / kedro-plugins, but would be useful to have it in the docs.

Would it be possible to make an issue over on the [Kedro](https://github.com/kedro-org/kedro/issues) list please with the docs you think are needed?

2023-10-09 10:08 UTC, hfwittmann commented
> > Its already implicity supported by kedro / kedro-plugins, but would be useful to have it in the docs.
> 
> Would it be possible to make an issue over on the [Kedro](https://github.com/kedro-org/kedro/issues) list please with the docs you think are needed?

Just to clarify: An issue or a pull-request (ie this same pull-request presumably)?

2023-10-09 10:38 UTC, stichbury commented
Hi @hfwittmann 

Hope this answers your question although I may have misinterpreted it. You wouldn't be able to make docs changes on this PR because the docs are in a different repo, and we don't expect you to do that task too, although of course it's great if can contribute the changes.

Feel free to raise an issue over on https://github.com/kedro-org/kedro/issues to record the fact the work is done and then, if you do want to do that change, feel free to make a separate PR.

Jo

2023-10-09 17:30 UTC, hfwittmann commented
> Hi @hfwittmann
> 
> Hope this answers your question although I may have misinterpreted it. You wouldn't be able to make docs changes on this PR because the docs are in a different repo, and we don't expect you to do that task too, although of course it's great if can contribute the changes.
> 
> Feel free to raise an issue over on https://github.com/kedro-org/kedro/issues to record the fact the work is done and then, if you do want to do that change, feel free to make a separate PR.
> 
> Jo

Excellent, I understand now.

Just to be clear, do I need to do this before the pull request is approved?

2023-10-10 09:06 UTC, stichbury commented
> Just to be clear, do I need to do this before the pull request is approved?

Hi @hfwittmann No, there's no dependency between them. I have re-requested review from @marrrcin as someone well-placed to assess your PR, and all being well, with second approval, we can merge your change.

2023-10-10 09:50 UTC, marrrcin approved these changes

2023-10-10 10:26 UTC, stichbury commented
@merelcht I didn't want to merge this without your signoff (it has 2 approvals but wanted to confirm it's OK to go in). Feel free to merge if you're happy!

2023-10-10 10:39 UTC, merelcht commented
> @merelcht I didn't want to merge this without your signoff (it has 2 approvals but wanted to confirm it's OK to go in). Feel free to merge if you're happy!

I updated the release notes and now it's all ready to go! 👍

2023-10-10 10:51 UTC, merged